export type Country = {
  code: string;
  name: string;
  dialCode: string;
  currencyCode: string;
  currencySymbol: string;
};

export const countries: Country[] = [
  { code: "AF", name: "Afghanistan", dialCode: "+93", currencyCode: "AFN", currencySymbol: "؋" },
  { code: "AL", name: "Albania", dialCode: "+355", currencyCode: "ALL", currencySymbol: "L" },
  { code: "DZ", name: "Algeria", dialCode: "+213", currencyCode: "DZD", currencySymbol: "د.ج" },
  { code: "AS", name: "American Samoa", dialCode: "+1684", currencyCode: "USD", currencySymbol: "$" },
  { code: "AD", name: "Andorra", dialCode: "+376", currencyCode: "EUR", currencySymbol: "€" },
  { code: "AO", name: "Angola", dialCode: "+244", currencyCode: "AOA", currencySymbol: "Kz" },
  { code: "AI", name: "Anguilla", dialCode: "+1264", currencyCode: "XCD", currencySymbol: "$" },
  { code: "AG", name: "Antigua and Barbuda", dialCode: "+1268", currencyCode: "XCD", currencySymbol: "$" },
  { code: "AR", name: "Argentina", dialCode: "+54", currencyCode: "ARS", currencySymbol: "$" },
  { code: "AM", name: "Armenia", dialCode: "+374", currencyCode: "AMD", currencySymbol: "֏" },
  { code: "AW", name: "Aruba", dialCode: "+297", currencyCode: "AWG", currencySymbol: "ƒ" },
  { code: "AU", name: "Australia", dialCode: "+61", currencyCode: "AUD", currencySymbol: "$" },
  { code: "AT", name: "Austria", dialCode: "+43", currencyCode: "EUR", currencySymbol: "€" },
  { code: "AZ", name: "Azerbaijan", dialCode: "+994", currencyCode: "AZN", currencySymbol: "₼" },
  { code: "BS", name: "Bahamas", dialCode: "+1242", currencyCode: "BSD", currencySymbol: "$" },
  { code: "BH", name: "Bahrain", dialCode: "+973", currencyCode: "BHD", currencySymbol: "د.ب" },
  { code: "BD", name: "Bangladesh", dialCode: "+880", currencyCode: "BDT", currencySymbol: "৳" },
  { code: "BB", name: "Barbados", dialCode: "+1246", currencyCode: "BBD", currencySymbol: "$" },
  { code: "BY", name: "Belarus", dialCode: "+375", currencyCode: "BYN", currencySymbol: "Br" },
  { code: "BE", name: "Belgium", dialCode: "+32", currencyCode: "EUR", currencySymbol: "€" },
  { code: "BZ", name: "Belize", dialCode: "+501", currencyCode: "BZD", currencySymbol: "$" },
  { code: "BJ", name: "Benin", dialCode: "+229", currencyCode: "XOF", currencySymbol: "Fr" },
  { code: "BM", name: "Bermuda", dialCode: "+1441", currencyCode: "BMD", currencySymbol: "$" },
  { code: "BT", name: "Bhutan", dialCode: "+975", currencyCode: "BTN", currencySymbol: "Nu." },
  { code: "BO", name: "Bolivia", dialCode: "+591", currencyCode: "BOB", currencySymbol: "Bs." },
  { code: "BA", name: "Bosnia and Herzegovina", dialCode: "+387", currencyCode: "BAM", currencySymbol: "KM" },
  { code: "BW", name: "Botswana", dialCode: "+267", currencyCode: "BWP", currencySymbol: "P" },
  { code: "BR", name: "Brazil", dialCode: "+55", currencyCode: "BRL", currencySymbol: "R$" },
  { code: "IO", name: "British Indian Ocean Territory", dialCode: "+246", currencyCode: "USD", currencySymbol: "$" },
  { code: "BN", name: "Brunei", dialCode: "+673", currencyCode: "BND", currencySymbol: "$" },
  { code: "BG", name: "Bulgaria", dialCode: "+359", currencyCode: "BGN", currencySymbol: "лв" },
  { code: "BF", name: "Burkina Faso", dialCode: "+226", currencyCode: "XOF", currencySymbol: "Fr" },
  { code: "BI", name: "Burundi", dialCode: "+257", currencyCode: "BIF", currencySymbol: "Fr" },
  { code: "KH", name: "Cambodia", dialCode: "+855", currencyCode: "KHR", currencySymbol: "៛" },
  { code: "CM", name: "Cameroon", dialCode: "+237", currencyCode: "XAF", currencySymbol: "Fr" },
  { code: "CA", name: "Canada", dialCode: "+1", currencyCode: "CAD", currencySymbol: "$" },
  { code: "CV", name: "Cape Verde", dialCode: "+238", currencyCode: "CVE", currencySymbol: "$" },
  { code: "KY", name: "Cayman Islands", dialCode: "+1345", currencyCode: "KYD", currencySymbol: "$" },
  { code: "CF", name: "Central African Republic", dialCode: "+236", currencyCode: "XAF", currencySymbol: "Fr" },
  { code: "TD", name: "Chad", dialCode: "+235", currencyCode: "XAF", currencySymbol: "Fr" },
  { code: "CL", name: "Chile", dialCode: "+56", currencyCode: "CLP", currencySymbol: "$" },
  { code: "CN", name: "China", dialCode: "+86", currencyCode: "CNY", currencySymbol: "¥" },
  { code: "CX", name: "Christmas Island", dialCode: "+61", currencyCode: "AUD", currencySymbol: "$" },
  { code: "CC", name: "Cocos (Keeling) Islands", dialCode: "+61", currencyCode: "AUD", currencySymbol: "$" },
  { code: "CO", name: "Colombia", dialCode: "+57", currencyCode: "COP", currencySymbol: "$" },
  { code: "KM", name: "Comoros", dialCode: "+269", currencyCode: "KMF", currencySymbol: "Fr" },
  { code: "CG", name: "Congo", dialCode: "+242", currencyCode: "XAF", currencySymbol: "Fr" },
  { code: "CD", name: "Congo (DRC)", dialCode: "+243", currencyCode: "CDF", currencySymbol: "Fr" },
  { code: "CK", name: "Cook Islands", dialCode: "+682", currencyCode: "NZD", currencySymbol: "$" },
  { code: "CR", name: "Costa Rica", dialCode: "+506", currencyCode: "CRC", currencySymbol: "₡" },
  { code: "CI", name: "Côte d’Ivoire", dialCode: "+225", currencyCode: "XOF", currencySymbol: "Fr" },
  { code: "HR", name: "Croatia", dialCode: "+385", currencyCode: "EUR", currencySymbol: "€" },
  { code: "CU", name: "Cuba", dialCode: "+53", currencyCode: "CUP", currencySymbol: "$" },
  { code: "CW", name: "Curaçao", dialCode: "+599", currencyCode: "ANG", currencySymbol: "ƒ" },
  { code: "CY", name: "Cyprus", dialCode: "+357", currencyCode: "EUR", currencySymbol: "€" },
  { code: "CZ", name: "Czechia", dialCode: "+420", currencyCode: "CZK", currencySymbol: "Kč" },
  { code: "DK", name: "Denmark", dialCode: "+45", currencyCode: "DKK", currencySymbol: "kr" },
  { code: "DJ", name: "Djibouti", dialCode: "+253", currencyCode: "DJF", currencySymbol: "Fr" },
  { code: "DM", name: "Dominica", dialCode: "+1767", currencyCode: "XCD", currencySymbol: "$" },
  { code: "DO", name: "Dominican Republic", dialCode: "+1", currencyCode: "DOP", currencySymbol: "RD$" },
  { code: "EC", name: "Ecuador", dialCode: "+593", currencyCode: "USD", currencySymbol: "$" },
  { code: "EG", name: "Egypt", dialCode: "+20", currencyCode: "EGP", currencySymbol: "£" },
  { code: "SV", name: "El Salvador", dialCode: "+503", currencyCode: "USD", currencySymbol: "$" },
  { code: "GQ", name: "Equatorial Guinea", dialCode: "+240", currencyCode: "XAF", currencySymbol: "Fr" },
  { code: "ER", name: "Eritrea", dialCode: "+291", currencyCode: "ERN", currencySymbol: "Nfk" },
  { code: "EE", name: "Estonia", dialCode: "+372", currencyCode: "EUR", currencySymbol: "€" },
  { code: "SZ", name: "Eswatini", dialCode: "+268", currencyCode: "SZL", currencySymbol: "L" },
  { code: "ET", name: "Ethiopia", dialCode: "+251", currencyCode: "ETB", currencySymbol: "Br" },
  { code: "FK", name: "Falkland Islands", dialCode: "+500", currencyCode: "FKP", currencySymbol: "£" },
  { code: "FO", name: "Faroe Islands", dialCode: "+298", currencyCode: "DKK", currencySymbol: "kr" },
  { code: "FJ", name: "Fiji", dialCode: "+679", currencyCode: "FJD", currencySymbol: "$" },
  { code: "FI", name: "Finland", dialCode: "+358", currencyCode: "EUR", currencySymbol: "€" },
  { code: "FR", name: "France", dialCode: "+33", currencyCode: "EUR", currencySymbol: "€" },
  { code: "GF", name: "French Guiana", dialCode: "+594", currencyCode: "EUR", currencySymbol: "€" },
  { code: "PF", name: "French Polynesia", dialCode: "+689", currencyCode: "XPF", currencySymbol: "Fr" },
  { code: "GA", name: "Gabon", dialCode: "+241", currencyCode: "XAF", currencySymbol: "Fr" },
  { code: "GM", name: "Gambia", dialCode: "+220", currencyCode: "GMD", currencySymbol: "D" },
  { code: "GE", name: "Georgia", dialCode: "+995", currencyCode: "GEL", currencySymbol: "₾" },
  { code: "DE", name: "Germany", dialCode: "+49", currencyCode: "EUR", currencySymbol: "€" },
  { code: "GH", name: "Ghana", dialCode: "+233", currencyCode: "GHS", currencySymbol: "₵" },
  { code: "GI", name: "Gibraltar", dialCode: "+350", currencyCode: "GIP", currencySymbol: "£" },
  { code: "GR", name: "Greece", dialCode: "+30", currencyCode: "EUR", currencySymbol: "€" },
  { code: "GL", name: "Greenland", dialCode: "+299", currencyCode: "DKK", currencySymbol: "kr" },
  { code: "GD", name: "Grenada", dialCode: "+1473", currencyCode: "XCD", currencySymbol: "$" },
  { code: "GP", name: "Guadeloupe", dialCode: "+590", currencyCode: "EUR", currencySymbol: "€" },
  { code: "GU", name: "Guam", dialCode: "+1671", currencyCode: "USD", currencySymbol: "$" },
  { code: "GT", name: "Guatemala", dialCode: "+502", currencyCode: "GTQ", currencySymbol: "Q" },
  { code: "GG", name: "Guernsey", dialCode: "+44", currencyCode: "GBP", currencySymbol: "£" },
  { code: "GN", name: "Guinea", dialCode: "+224", currencyCode: "GNF", currencySymbol: "Fr" },
  { code: "GW", name: "Guinea-Bissau", dialCode: "+245", currencyCode: "XOF", currencySymbol: "Fr" },
  { code: "GY", name: "Guyana", dialCode: "+592", currencyCode: "GYD", currencySymbol: "$" },
  { code: "HT", name: "Haiti", dialCode: "+509", currencyCode: "HTG", currencySymbol: "G" },
  { code: "HN", name: "Honduras", dialCode: "+504", currencyCode: "HNL", currencySymbol: "L" },
  { code: "HK", name: "Hong Kong", dialCode: "+852", currencyCode: "HKD", currencySymbol: "$" },
  { code: "HU", name: "Hungary", dialCode: "+36", currencyCode: "HUF", currencySymbol: "Ft" },
  { code: "IS", name: "Iceland", dialCode: "+354", currencyCode: "ISK", currencySymbol: "kr" },
  { code: "IN", name: "India", dialCode: "+91", currencyCode: "INR", currencySymbol: "₹" },
  { code: "ID", name: "Indonesia", dialCode: "+62", currencyCode: "IDR", currencySymbol: "Rp" },
  { code: "IR", name: "Iran", dialCode: "+98", currencyCode: "IRR", currencySymbol: "﷼" },
  { code: "IQ", name: "Iraq", dialCode: "+964", currencyCode: "IQD", currencySymbol: "ع.د" },
  { code: "IE", name: "Ireland", dialCode: "+353", currencyCode: "EUR", currencySymbol: "€" },
  { code: "IM", name: "Isle of Man", dialCode: "+44", currencyCode: "GBP", currencySymbol: "£" },
  { code: "IL", name: "Israel", dialCode: "+972", currencyCode: "ILS", currencySymbol: "₪" },
  { code: "IT", name: "Italy", dialCode: "+39", currencyCode: "EUR", currencySymbol: "€" },
  { code: "JM", name: "Jamaica", dialCode: "+1876", currencyCode: "JMD", currencySymbol: "$" },
  { code: "JP", name: "Japan", dialCode: "+81", currencyCode: "JPY", currencySymbol: "¥" },
  { code: "JE", name: "Jersey", dialCode: "+44", currencyCode: "GBP", currencySymbol: "£" },
  { code: "JO", name: "Jordan", dialCode: "+962", currencyCode: "JOD", currencySymbol: "د.أ" },
  { code: "KZ", name: "Kazakhstan", dialCode: "+7", currencyCode: "KZT", currencySymbol: "₸" },
  { code: "KE", name: "Kenya", dialCode: "+254", currencyCode: "KES", currencySymbol: "Sh" },
  { code: "KI", name: "Kiribati", dialCode: "+686", currencyCode: "AUD", currencySymbol: "$" },
  { code: "XK", name: "Kosovo", dialCode: "+383", currencyCode: "EUR", currencySymbol: "€" },
  { code: "KW", name: "Kuwait", dialCode: "+965", currencyCode: "KWD", currencySymbol: "د.ك" },
  { code: "KG", name: "Kyrgyzstan", dialCode: "+996", currencyCode: "KGS", currencySymbol: "som" },
  { code: "LA", name: "Laos", dialCode: "+856", currencyCode: "LAK", currencySymbol: "₭" },
  { code: "LV", name: "Latvia", dialCode: "+371", currencyCode: "EUR", currencySymbol: "€" },
  { code: "LB", name: "Lebanon", dialCode: "+961", currencyCode: "LBP", currencySymbol: "ل.ل" },
  { code: "LS", name: "Lesotho", dialCode: "+266", currencyCode: "LSL", currencySymbol: "L" },
  { code: "LR", name: "Liberia", dialCode: "+231", currencyCode: "LRD", currencySymbol: "$" },
  { code: "LY", name: "Libya", dialCode: "+218", currencyCode: "LYD", currencySymbol: "ل.د" },
  { code: "LI", name: "Liechtenstein", dialCode: "+423", currencyCode: "CHF", currencySymbol: "Fr" },
  { code: "LT", name: "Lithuania", dialCode: "+370", currencyCode: "EUR", currencySymbol: "€" },
  { code: "LU", name: "Luxembourg", dialCode: "+352", currencyCode: "EUR", currencySymbol: "€" },
  { code: "MO", name: "Macao", dialCode: "+853", currencyCode: "MOP", currencySymbol: "P" },
  { code: "MG", name: "Madagascar", dialCode: "+261", currencyCode: "MGA", currencySymbol: "Ar" },
  { code: "MW", name: "Malawi", dialCode: "+265", currencyCode: "MWK", currencySymbol: "MK" },
  { code: "MY", name: "Malaysia", dialCode: "+60", currencyCode: "MYR", currencySymbol: "RM" },
  { code: "MV", name: "Maldives", dialCode: "+960", currencyCode: "MVR", currencySymbol: "ރ." },
  { code: "ML", name: "Mali", dialCode: "+223", currencyCode: "XOF", currencySymbol: "Fr" },
  { code: "MT", name: "Malta", dialCode: "+356", currencyCode: "EUR", currencySymbol: "€" },
  { code: "MH", name: "Marshall Islands", dialCode: "+692", currencyCode: "USD", currencySymbol: "$" },
  { code: "MQ", name: "Martinique", dialCode: "+596", currencyCode: "EUR", currencySymbol: "€" },
  { code: "MR", name: "Mauritania", dialCode: "+222", currencyCode: "MRU", currencySymbol: "UM" },
  { code: "MU", name: "Mauritius", dialCode: "+230", currencyCode: "MUR", currencySymbol: "₨" },
  { code: "YT", name: "Mayotte", dialCode: "+262", currencyCode: "EUR", currencySymbol: "€" },
  { code: "MX", name: "Mexico", dialCode: "+52", currencyCode: "MXN", currencySymbol: "$" },
  { code: "FM", name: "Micronesia", dialCode: "+691", currencyCode: "USD", currencySymbol: "$" },
  { code: "MD", name: "Moldova", dialCode: "+373", currencyCode: "MDL", currencySymbol: "L" },
  { code: "MC", name: "Monaco", dialCode: "+377", currencyCode: "EUR", currencySymbol: "€" },
  { code: "MN", name: "Mongolia", dialCode: "+976", currencyCode: "MNT", currencySymbol: "₮" },
  { code: "ME", name: "Montenegro", dialCode: "+382", currencyCode: "EUR", currencySymbol: "€" },
  { code: "MS", name: "Montserrat", dialCode: "+1664", currencyCode: "XCD", currencySymbol: "$" },
  { code: "MA", name: "Morocco", dialCode: "+212", currencyCode: "MAD", currencySymbol: "د.م." },
  { code: "MZ", name: "Mozambique", dialCode: "+258", currencyCode: "MZN", currencySymbol: "MT" },
  { code: "MM", name: "Myanmar", dialCode: "+95", currencyCode: "MMK", currencySymbol: "K" },
  { code: "NA", name: "Namibia", dialCode: "+264", currencyCode: "NAD", currencySymbol: "$" },
  { code: "NR", name: "Nauru", dialCode: "+674", currencyCode: "AUD", currencySymbol: "$" },
  { code: "NP", name: "Nepal", dialCode: "+977", currencyCode: "NPR", currencySymbol: "₨" },
  { code: "NL", name: "Netherlands", dialCode: "+31", currencyCode: "EUR", currencySymbol: "€" },
  { code: "NC", name: "New Caledonia", dialCode: "+687", currencyCode: "XPF", currencySymbol: "Fr" },
  { code: "NZ", name: "New Zealand", dialCode: "+64", currencyCode: "NZD", currencySymbol: "$" },
  { code: "NI", name: "Nicaragua", dialCode: "+505", currencyCode: "NIO", currencySymbol: "C$" },
  { code: "NE", name: "Niger", dialCode: "+227", currencyCode: "XOF", currencySymbol: "Fr" },
  { code: "NG", name: "Nigeria", dialCode: "+234", currencyCode: "NGN", currencySymbol: "₦" },
  { code: "NU", name: "Niue", dialCode: "+683", currencyCode: "NZD", currencySymbol: "$" },
  { code: "NF", name: "Norfolk Island", dialCode: "+672", currencyCode: "AUD", currencySymbol: "$" },
  { code: "KP", name: "North Korea", dialCode: "+850", currencyCode: "KPW", currencySymbol: "₩" },
  { code: "MK", name: "North Macedonia", dialCode: "+389", currencyCode: "MKD", currencySymbol: "ден" },
  { code: "MP", name: "Northern Mariana Islands", dialCode: "+1670", currencyCode: "USD", currencySymbol: "$" },
  { code: "NO", name: "Norway", dialCode: "+47", currencyCode: "NOK", currencySymbol: "kr" },
  { code: "OM", name: "Oman", dialCode: "+968", currencyCode: "OMR", currencySymbol: "ر.ع." },
  { code: "PK", name: "Pakistan", dialCode: "+92", currencyCode: "PKR", currencySymbol: "₨" },
  { code: "PW", name: "Palau", dialCode: "+680", currencyCode: "USD", currencySymbol: "$" },
  { code: "PS", name: "Palestine", dialCode: "+970", currencyCode: "ILS", currencySymbol: "₪" },
  { code: "PA", name: "Panama", dialCode: "+507", currencyCode: "PAB", currencySymbol: "B/." },
  { code: "PG", name: "Papua New Guinea", dialCode: "+675", currencyCode: "PGK", currencySymbol: "K" },
  { code: "PY", name: "Paraguay", dialCode: "+595", currencyCode: "PYG", currencySymbol: "₲" },
  { code: "PE", name: "Peru", dialCode: "+51", currencyCode: "PEN", currencySymbol: "S/" },
  { code: "PH", name: "Philippines", dialCode: "+63", currencyCode: "PHP", currencySymbol: "₱" },
  { code: "PL", name: "Poland", dialCode: "+48", currencyCode: "PLN", currencySymbol: "zł" },
  { code: "PT", name: "Portugal", dialCode: "+351", currencyCode: "EUR", currencySymbol: "€" },
  { code: "PR", name: "Puerto Rico", dialCode: "+1", currencyCode: "USD", currencySymbol: "$" },
  { code: "QA", name: "Qatar", dialCode: "+974", currencyCode: "QAR", currencySymbol: "ر.ق" },
  { code: "RE", name: "Réunion", dialCode: "+262", currencyCode: "EUR", currencySymbol: "€" },
  { code: "RO", name: "Romania", dialCode: "+40", currencyCode: "RON", currencySymbol: "lei" },
  { code: "RU", name: "Russia", dialCode: "+7", currencyCode: "RUB", currencySymbol: "₽" },
  { code: "RW", name: "Rwanda", dialCode: "+250", currencyCode: "RWF", currencySymbol: "Fr" },
  { code: "BL", name: "Saint Barthélemy", dialCode: "+590", currencyCode: "EUR", currencySymbol: "€" },
  { code: "SH", name: "Saint Helena", dialCode: "+290", currencyCode: "SHP", currencySymbol: "£" },
  { code: "KN", name: "Saint Kitts and Nevis", dialCode: "+1869", currencyCode: "XCD", currencySymbol: "$" },
  { code: "LC", name: "Saint Lucia", dialCode: "+1758", currencyCode: "XCD", currencySymbol: "$" },
  { code: "MF", name: "Saint Martin", dialCode: "+590", currencyCode: "EUR", currencySymbol: "€" },
  { code: "PM", name: "Saint Pierre and Miquelon", dialCode: "+508", currencyCode: "EUR", currencySymbol: "€" },
  { code: "VC", name: "Saint Vincent and the Grenadines", dialCode: "+1784", currencyCode: "XCD", currencySymbol: "$" },
  { code: "WS", name: "Samoa", dialCode: "+685", currencyCode: "WST", currencySymbol: "T" },
  { code: "SM", name: "San Marino", dialCode: "+378", currencyCode: "EUR", currencySymbol: "€" },
  { code: "ST", name: "São Tomé and Príncipe", dialCode: "+239", currencyCode: "STN", currencySymbol: "Db" },
  { code: "SA", name: "Saudi Arabia", dialCode: "+966", currencyCode: "SAR", currencySymbol: "ر.س" },
  { code: "SN", name: "Senegal", dialCode: "+221", currencyCode: "XOF", currencySymbol: "Fr" },
  { code: "RS", name: "Serbia", dialCode: "+381", currencyCode: "RSD", currencySymbol: "дин" },
  { code: "SC", name: "Seychelles", dialCode: "+248", currencyCode: "SCR", currencySymbol: "₨" },
  { code: "SL", name: "Sierra Leone", dialCode: "+232", currencyCode: "SLE", currencySymbol: "Le" },
  { code: "SG", name: "Singapore", dialCode: "+65", currencyCode: "SGD", currencySymbol: "$" },
  { code: "SX", name: "Sint Maarten", dialCode: "+1721", currencyCode: "ANG", currencySymbol: "ƒ" },
  { code: "SK", name: "Slovakia", dialCode: "+421", currencyCode: "EUR", currencySymbol: "€" },
  { code: "SI", name: "Slovenia", dialCode: "+386", currencyCode: "EUR", currencySymbol: "€" },
  { code: "SB", name: "Solomon Islands", dialCode: "+677", currencyCode: "SBD", currencySymbol: "$" },
  { code: "SO", name: "Somalia", dialCode: "+252", currencyCode: "SOS", currencySymbol: "Sh" },
  { code: "ZA", name: "South Africa", dialCode: "+27", currencyCode: "ZAR", currencySymbol: "R" },
  { code: "GS", name: "South Georgia and the South Sandwich Islands", dialCode: "+500", currencyCode: "GBP", currencySymbol: "£" },
  { code: "KR", name: "South Korea", dialCode: "+82", currencyCode: "KRW", currencySymbol: "₩" },
  { code: "SS", name: "South Sudan", dialCode: "+211", currencyCode: "SSP", currencySymbol: "£" },
  { code: "ES", name: "Spain", dialCode: "+34", currencyCode: "EUR", currencySymbol: "€" },
  { code: "LK", name: "Sri Lanka", dialCode: "+94", currencyCode: "LKR", currencySymbol: "₨" },
  { code: "SD", name: "Sudan", dialCode: "+249", currencyCode: "SDG", currencySymbol: "£" },
  { code: "SR", name: "Suriname", dialCode: "+597", currencyCode: "SRD", currencySymbol: "$" },
  { code: "SJ", name: "Svalbard and Jan Mayen", dialCode: "+47", currencyCode: "NOK", currencySymbol: "kr" },
  { code: "SE", name: "Sweden", dialCode: "+46", currencyCode: "SEK", currencySymbol: "kr" },
  { code: "CH", name: "Switzerland", dialCode: "+41", currencyCode: "CHF", currencySymbol: "Fr" },
  { code: "SY", name: "Syria", dialCode: "+963", currencyCode: "SYP", currencySymbol: "£" },
  { code: "TW", name: "Taiwan", dialCode: "+886", currencyCode: "TWD", currencySymbol: "$" },
  { code: "TJ", name: "Tajikistan", dialCode: "+992", currencyCode: "TJS", currencySymbol: "ЅМ" },
  { code: "TZ", name: "Tanzania", dialCode: "+255", currencyCode: "TZS", currencySymbol: "Sh" },
  { code: "TH", name: "Thailand", dialCode: "+66", currencyCode: "THB", currencySymbol: "฿" },
  { code: "TL", name: "Timor-Leste", dialCode: "+670", currencyCode: "USD", currencySymbol: "$" },
  { code: "TG", name: "Togo", dialCode: "+228", currencyCode: "XOF", currencySymbol: "Fr" },
  { code: "TK", name: "Tokelau", dialCode: "+690", currencyCode: "NZD", currencySymbol: "$" },
  { code: "TO", name: "Tonga", dialCode: "+676", currencyCode: "TOP", currencySymbol: "T$" },
  { code: "TT", name: "Trinidad and Tobago", dialCode: "+1868", currencyCode: "TTD", currencySymbol: "$" },
  { code: "TN", name: "Tunisia", dialCode: "+216", currencyCode: "TND", currencySymbol: "د.ت" },
  { code: "TR", name: "Türkiye", dialCode: "+90", currencyCode: "TRY", currencySymbol: "₺" },
  { code: "TM", name: "Turkmenistan", dialCode: "+993", currencyCode: "TMT", currencySymbol: "m" },
  { code: "TC", name: "Turks and Caicos Islands", dialCode: "+1649", currencyCode: "USD", currencySymbol: "$" },
  { code: "TV", name: "Tuvalu", dialCode: "+688", currencyCode: "AUD", currencySymbol: "$" },
  { code: "UG", name: "Uganda", dialCode: "+256", currencyCode: "UGX", currencySymbol: "Sh" },
  { code: "UA", name: "Ukraine", dialCode: "+380", currencyCode: "UAH", currencySymbol: "₴" },
  { code: "AE", name: "United Arab Emirates", dialCode: "+971", currencyCode: "AED", currencySymbol: "د.إ" },
  { code: "GB", name: "United Kingdom", dialCode: "+44", currencyCode: "GBP", currencySymbol: "£" },
  { code: "US", name: "United States", dialCode: "+1", currencyCode: "USD", currencySymbol: "$" },
  { code: "UM", name: "United States Minor Outlying Islands", dialCode: "+1", currencyCode: "USD", currencySymbol: "$" },
  { code: "UY", name: "Uruguay", dialCode: "+598", currencyCode: "UYU", currencySymbol: "$" },
  { code: "UZ", name: "Uzbekistan", dialCode: "+998", currencyCode: "UZS", currencySymbol: "so'm" },
  { code: "VU", name: "Vanuatu", dialCode: "+678", currencyCode: "VUV", currencySymbol: "Vt" },
  { code: "VA", name: "Vatican City", dialCode: "+379", currencyCode: "EUR", currencySymbol: "€" },
  { code: "VE", name: "Venezuela", dialCode: "+58", currencyCode: "VES", currencySymbol: "Bs." },
  { code: "VN", name: "Vietnam", dialCode: "+84", currencyCode: "VND", currencySymbol: "₫" },
  { code: "VG", name: "Virgin Islands (British)", dialCode: "+1284", currencyCode: "USD", currencySymbol: "$" },
  { code: "VI", name: "Virgin Islands (U.S.)", dialCode: "+1340", currencyCode: "USD", currencySymbol: "$" },
  { code: "WF", name: "Wallis and Futuna", dialCode: "+681", currencyCode: "XPF", currencySymbol: "Fr" },
  { code: "EH", name: "Western Sahara", dialCode: "+212", currencyCode: "MAD", currencySymbol: "د.م." },
  { code: "YE", name: "Yemen", dialCode: "+967", currencyCode: "YER", currencySymbol: "﷼" },
  { code: "ZM", name: "Zambia", dialCode: "+260", currencyCode: "ZMW", currencySymbol: "K" },
  { code: "ZW", name: "Zimbabwe", dialCode: "+263", currencyCode: "ZWL", currencySymbol: "$" },
];

export const dialCodes = Array.from(
  new Map(countries.map((country) => [country.dialCode, country])).values(),
).map((country) => ({
  dialCode: country.dialCode,
  countryName: country.name,
}));

export function getCountryByCode(code: string): Country | undefined {
  return countries.find((country) => country.code === code);
}

export function getCountryByDialCode(dialCode: string): Country | undefined {
  return countries.find((country) => country.dialCode === dialCode);
}
